############################# Default configuration ########################
baseURL = "http://docs.improving.app/"
title = "improving.app | Fully functional demonstration application"
theme = "small-apps-hugo"
# post pagination
paginate = "6"
# post excerpt
summaryLength = "10"
# disable language
disableLanguages = ["french"] # desable language from here

################################### Plugins #################################
# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themefisher-font/themefisher-font.min.css"
[[params.plugins.css]]
link = "plugins/owl-carousel/owl.carousel.min.css"
[[params.plugins.css]]
link = "plugins/aos/aos.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jquery/jquery.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/owl-carousel/owl.carousel.min.js"
[[params.plugins.js]]
link = "plugins/aos/aos.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"


############################ Navigation English #################################
# main menu
[[Languages.en.menu.main]]
name = "About"
URL = "about"
weight = 1

[[Languages.en.menu.main]]
name = "team"
URL = "team"
weight = 2

[[Languages.en.menu.main]]
name = "Blog"
URL = "blog"
weight = 3

[[Languages.en.menu.main]]
name = "career"
URL = "career"
weight = 4

[[Languages.en.menu.main]]
name = "Contact"
URL = "contact"
weight = 5

# dropdown menu
[[Languages.en.menu.main]]
name = "Pages"
weight = 6
hasChildren = true

  [[Languages.en.menu.main]]
  parent = "Pages"
  name = "privacy"
  URL = "privacy"
  weight = 1

  [[Languages.en.menu.main]]
  parent = "Pages"
  name = "FAQ"
  URL = "faq"
  weight = 2


# footer menu
[[Languages.en.menu.footer]]
name = "About"
URL = "about"

[[Languages.en.menu.footer]]
name = "Contact"
URL = "contact"

[[Languages.en.menu.footer]]
name = "Privacy"
URL = "privacy"

[[Languages.en.menu.footer]]
name = "Blog"
URL = "blog"

[[Languages.en.menu.footer]]
name = "FAQ"
URL = "faq"

############################ Navigation French #################################
# main menu
[[Languages.fr.menu.main]]
name = "À propos"
URL = "about"
weight = 1

[[Languages.fr.menu.main]]
name = "Équipe"
URL = "team"
weight = 2

[[Languages.fr.menu.main]]
name = "Blog"
URL = "blog"
weight = 3

[[Languages.fr.menu.main]]
name = "Carrière"
URL = "career"
weight = 4

[[Languages.fr.menu.main]]
name = "Contact"
URL = "contact"
weight = 5

# dropdown menu
[[Languages.fr.menu.main]]
name = "Pages"
weight = 6
hasChildren = true

  [[Languages.fr.menu.main]]
  parent = "Pages"
  name = "Intimité"
  URL = "privacy"
  weight = 1

  [[Languages.fr.menu.main]]
  parent = "Pages"
  name = "FAQ"
  URL = "faq"
  weight = 2


# footer menu
[[Languages.fr.menu.footer]]
name = "À propos"
URL = "about"

[[Languages.fr.menu.footer]]
name = "Contact"
URL = "contact"

[[Languages.fr.menu.footer]]
name = "Intimité"
URL = "privacy"

[[Languages.fr.menu.footer]]
name = "Blog"
URL = "blog"

[[Languages.fr.menu.footer]]
name = "FAQ"
URL = "faq"


########################### Default parameters ###########################
[params]
# main logo
logo = "images/logo.png"
# footer logo
logo_light = "images/logo-alt.png"
home = "Home"
# Meta data
description = "Documentation For the "
author = "The improving.app Team"
# contact info
address = ""
mobile = "+211234565523"
email = "info@yoppworks.com"
# contact form action
contact_form_action = "#" # contact form works with https://formspree.io
# Google Analitycs
google_analitycs_id = "" # Your ID

# Preloader
[params.preloader]
enable = true
preloader = "" # use jpg,png,svg or gif format

# google map
[params.map]
enable = true
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBu5nZKbeK-WHQ70oqOWo-_4VmwOwKP9YQ"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"


########################### social icon ############################
[[params.social]]
icon = "tf-ion-social-facebook"
link = "https://facebook.com/Yoppworks"

[[params.social]]
icon = "tf-ion-social-twitter"
link = "https://twitter.com/yoppworks"

[[params.social]]
icon = "tf-ion-social-linkedIn"
link = "https://linkedin.com/yoppworks"


################################### English language #####################################
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
home = "Home"


################################### French language #####################################
[Languages.fr]
languageName = "Fr"
languageCode = "fr-fr"
contentDir = "content/french"
weight = 2
home = "Accueil"